package vn.edu.fsoftacademy.api.api.rest.shared.error;

/** Stable, machine-readable codes exposed by API error responses. */
public enum ApiErrorCode {
  VALIDATION_FAILED,
  MALFORMED_REQUEST,
  MISSING_REQUEST_VALUE,
  INVALID_PARAMETER,
  METHOD_NOT_ALLOWED,
  UNSUPPORTED_MEDIA_TYPE,
  ENDPOINT_NOT_FOUND,
  EMAIL_ALREADY_EXISTS,
  PROJECT_NOT_FOUND,
  DOCUMENT_NOT_FOUND,
  DOCUMENT_CONTENT_NOT_AVAILABLE,
  INVALID_CREDENTIALS,
  INVALID_REFRESH_TOKEN,
  AUTHENTICATION_REQUIRED,
  ACCESS_TOKEN_EXPIRED,
  ACCESS_TOKEN_INVALID,
  ACCESS_DENIED,
  STORAGE_ERROR,
  CONVERSATION_NOT_FOUND,
  AI_PROVIDER_UNAVAILABLE,
  INTERNAL_SERVER_ERROR
}
